Session management
wolox-training/jhen-react pull request #8
Opened 2022-09-06 15:37 UTC by Julianhm9612

## Summary

- Added NavBar component
- Added Home screen
- Added redirects to Home
- Configured session management with localStorage

## Screenshots

![Session management](https://user-images.githubusercontent.com/24255842/188676295-9dc9894b-395a-464e-bb3e-4f09ec3b3dc1.gif)

## Trello Card

https://trello.com/c/VkXa68Vk/15-session-management-logout

2022-09-06 16:07 UTC, ebedoyaalzate requested changes

2022-09-06 16:07 UTC, ebedoyaalzate commented on src/components/NavBar/index.tsx
> +    <div className={styles.navbar}>
this div is unnecessary

2022-09-06 16:07 UTC, ebedoyaalzate commented on src/components/NavBar/index.tsx
> +          Logout
add i18n

2022-09-06 16:07 UTC, ebedoyaalzate commented on src/components/NavBar/styles.module.scss
> +    top: 0;
two spaces of tab

2022-09-06 21:42 UTC, Julianhm9612 commented on src/components/NavBar/index.tsx
> +    <div className={styles.navbar}>
Has been deleted and improved :godmode:

2022-09-06 21:42 UTC, Julianhm9612 commented on src/components/NavBar/index.tsx
> +          Logout
Has been added :godmode:

2022-09-06 21:43 UTC, Julianhm9612 commented on src/components/NavBar/styles.module.scss
> +    top: 0;
Has been solved :godmode:

2022-09-09 16:04 UTC, ebedoyaalzate requested changes

2022-09-09 16:04 UTC, ebedoyaalzate commented on src/components/NavBar/styles.module.scss
> +}
empty line

2022-09-09 16:04 UTC, ebedoyaalzate commented on src/screens/Home/index.tsx
> +    <div className={styles.home}>
do you need this div?

2022-09-09 16:05 UTC, ebedoyaalzate approved these changes

2022-09-09 16:37 UTC, Julianhm9612 commented on src/components/NavBar/styles.module.scss
> +}
My mistake! Has been solved :godmode:

2022-09-09 16:39 UTC, merged